function dolc()  {  
    document.getElementById('info').innerHTML = ""
+"<body class='cuerpo'><br>"
    +"<center>"
       +"<section>"
            +"<h2><p class='oscar'>REGISTRAR CLIENTE</p></h2>"
            +"<input class='cons' type='text' name='TIPO DE DOCUMENTACIÓN'  placeholder='TIPO DE DOCUMENTACIÓN'><br>"
            +"<input class='cons' type='text' name='NOMBRES'  placeholder='NOMBRES'><br>"
            +"<input class='cons' type='text' name='APELLIDOS'  placeholder='APELLIDOS'><br>"
            +"<input class='cons' type='text' name='CELULAR'  placeholder='CELULAR'><br>"
            +"<input class='cons' type='text' name='CONTRASEÑA' placeholder='CONTRASEÑA'><br><br><br><br>"
            +"<a class='piedra' href='menú.html'>REGISTRAR</a>"
        +"</section>"
    +"</center>";
    }

    function dolc1() {
    document.getElementById('info').innerHTML = ""
    +"<body class='cuerpo'>"
    +"<center><h1><p class='oscar'>BIENVENIDO</p></h1></center>"
    +"<div class='dropdown'>"
        +"<button class='dropbtn'><a href='index.html'>INICIO</a></button>"
     +"</div>"
              "</div>"
        +"<div class='dropdown'>"
            +"<button class='dropbtn'>CLIENTE</button>"
            +"<div class='dropdown-content'>"
            +"<a href='agregar cliente.html' onclick='dolc()'>AGREGAR</a>"
           +"<a href='consultar y listar.html' onclick='dolc1()'>CONSULTAR</a>"
            +"<a href='consultar y listar.html' onclick='dolc2()'>LISTAR</a>"
           +"</div>"
          +"</div>"
        +"<div class='dropdown'>"
            +"<button class='dropbtn'>CARROS</button>"
            +"<div class='dropdown-content'>"
            +"<a href='agregar carros.html'>AGREGAR</a>"
            +"<a href='#'>CONSULTAR</a>"
            +"<a href='#'>LISTAR</a>"
            +"</div>"
        +"</div>"
        +"<div class='dropdown'>"
            +"<button class='dropbtn'>SERVICIOS</button>"
            +"<div class='dropdown-content'>"
            +"<a href='agregar servicios.html'>AGREGAR</a>"
            +"<a href='#'>CONSULTAR</a>"
            +"<a href='#'>LISTAR</a>"
            +"</div>"
        +"</div>"
+"<div class='dropdown'>"
 +"<button class='dropbtn'>AYUDA</button>"
 +"<div class='dropdown-content'>"
    +"<a href='reporte.html'>REPORTE</a>"
+"</div>"
+"</div>"
+"<div class='dropdown'>"
    +"<button class='dropbtn'><a href='index.html'>SALIR</a></button>"
 +"</div>"
          +"</div>";
 }        
 function dolc1() {
    document.getElementById("info").innerHTML = "" 
    +"<body class='cuerpo'>"
    +"<center><h2><p class='oscar'>CONSULTAR CLIENTES</p></h2></center>"
+"<center>"
   +"<form action='../../form-result.php' method='post' target='_blank'>"
    +"<p class='oscar'>"
     +"CONSULTAR <input type='search' name='busqueda' placeholder='identificacion, nombres, telefono...'>"
     +"<a class='piedra2' href=''>BUSCAR</a>"
    +"</p>"
  +"</form>"
+"</center>"
+"<style>"
    +"table,th,td{"
        +"border: 1px solid rgb(255, 250, 250);"
    +"}"
+"</style>"
+"<br>"
+"<center>"
+"<table class='and'>"
    +"<tr class='oscar'>"
      +"<th>N°</th>"
      +"<th>IDENTIFICACIÓN</th>"
      +"<th>NOMBRES</th>"
      +"<th>TELÉFONO</th>"
      +"<th>APELLIDOS</th>"
    +"</tr>"
    +"<tr class='oscar'>"
        +"<td>1</td>"
        +"<td>2</td>"
        +"<td>3</td>"
        +"<td>4</td>"
       +"<td>5</td>"
    +"</tr> <tr class='oscar'>"
        +"<td>1</td>"
        +"<td>2</td>"
        +"<td>3</td>"
        +"<td>4</td>"
        +"<td>5</td>"
    +"</tr> <tr class='oscar'>"
        +"<td>1</td>"
        +"<td>2</td>"
        +"<td>3</td>"
        +"<td>4</td>"
        +"<td>5</td>"
    +"</tr> <tr class='oscar'>"
        +"<td>1</td>"
        +"<td>2</td>"
        +"<td>3</td>"
        +"<td>4</td>"
        +"<td>5</td>"
    +"</tr>"
    +"</tr> <tr class='oscar'>"
        +"<td>1</td>"
        +"<td>2</td>"
        +"<td>3</td>"
        +"<td>4</td>"
        +"<td>5</td>"
    +"</tr>"
    +"</tr> <tr class='oscar'>"
    +"<td>1</td>"
    +"<td>2</td>"
    +"<td>3</td>"
    +"<td>4</td>"
    +"<td>5</td>"
+"</tr>"
+"</tr> <tr class='oscar'>"
+"<td>1</td>"
+"<td>2</td>"
+"<td>3</td>"
+"<td>4</td>"
+"<td>5</td>"
+"</tr>"
  +"</table>"
+"</center>";
 }
 function dolc2() {
    document.getElementById("info").innerHTML = "" 
    +"<body class='cuerpo'>"
    +"<center><h2><p class='oscar'>LISTAR CLIENTES</p></h2></center>"
+"<center>"
   +"<form action='../../form-result.php' method='post' target='_blank'>"
    +"<p class='oscar'>"
     +"CONSULTAR <input type='search' name='busqueda' placeholder='identificacion, nombres, telefono...'>"
     +"<a class='piedra2' href=''>BUSCAR</a>"
    +"</p>"
  +"</form>"
+"</center>"
+"<style>"
    +"table,th,td{"
        +"border: 1px solid rgb(255, 250, 250);"
    +"}"
+"</style>"
+"<br>"
+"<center>"
+"<table class='and'>"
    +"<tr class='oscar'>"
      +"<th>N°</th>"
      +"<th>IDENTIFICACIÓN</th>"
      +"<th>NOMBRES</th>"
      +"<th>TELÉFONO</th>"
      +"<th>APELLIDOS</th>"
    +"</tr>"
    +"<tr class='oscar'>"
        +"<td>1</td>"
        +"<td>2</td>"
        +"<td>3</td>"
        +"<td>4</td>"
       +"<td>5</td>"
    +"</tr> <tr class='oscar'>"
        +"<td>1</td>"
        +"<td>2</td>"
        +"<td>3</td>"
        +"<td>4</td>"
        +"<td>5</td>"
    +"</tr> <tr class='oscar'>"
        +"<td>1</td>"
        +"<td>2</td>"
        +"<td>3</td>"
        +"<td>4</td>"
        +"<td>5</td>"
    +"</tr> <tr class='oscar'>"
        +"<td>1</td>"
        +"<td>2</td>"
        +"<td>3</td>"
        +"<td>4</td>"
        +"<td>5</td>"
    +"</tr>"
    +"</tr> <tr class='oscar'>"
        +"<td>1</td>"
        +"<td>2</td>"
        +"<td>3</td>"
        +"<td>4</td>"
        +"<td>5</td>"
    +"</tr>"
    +"</tr> <tr class='oscar'>"
    +"<td>1</td>"
    +"<td>2</td>"
    +"<td>3</td>"
    +"<td>4</td>"
    +"<td>5</td>"
+"</tr>"
+"</tr> <tr class='oscar'>"
+"<td>1</td>"
+"<td>2</td>"
+"<td>3</td>"
+"<td>4</td>"
+"<td>5</td>"
+"</tr>"
  +"</table>"
+"</center>";
 }
 function pero() {
    document.getElementById("info").innerHTML = "" 
    +"<body class='cuerpo'><br>"
        +"<center>"
            +"<section>"
               +"<h2><p class='oscar'>REGISTRAR CARRO</p></h2>"
                +"<input class='cons' type='text' name='PLACA'  placeholder='PLACA'><br>"
                +"<input class='cons' type='text' name='MARCA'  placeholder='MARCA'><br>"
                +"<input class='cons' type='text' name='MODELO'  placeholder='MODELO'><br><br><br><br>"
                +"<a class='piedra' href='menú.html'>REGISTRAR</a>"
            +"</section>"
        +"</center>"
 }
 function pero1() {
    document.getElementById("info").innerHTML = "" 
    +"<body class='cuerpo'>"
    +"<center><h2><p class='oscar'>CONSULTAR CARROS</p></h2></center>"
+"<center>"
   +"<form action='../../form-result.php' method='post' target='_blank'>"
    +"<p class='oscar'>"
     +"CONSULTAR <input type='search' name='busqueda' placeholder='identificacion, nombres, telefono...'>"
     +"<a class='piedra2' href=''>BUSCAR</a>"
    +"</p>"
  +"</form>"
+"</center>"
+"<style>"
    +"table,th,td{"
        +"border: 1px solid rgb(255, 250, 250);"
    +"}"
+"</style>"
+"<br>"
+"<center>"
+"<table class='and'>"
    +"<tr class='oscar'>"
      +"<th>N°</th>"
      +"<th>IDENTIFICACIÓN</th>"
      +"<th>NOMBRES</th>"
      +"<th>TELÉFONO</th>"
      +"<th>APELLIDOS</th>"
    +"</tr>"
    +"<tr class='oscar'>"
        +"<td>1</td>"
        +"<td>2</td>"
        +"<td>3</td>"
        +"<td>4</td>"
       +"<td>5</td>"
    +"</tr> <tr class='oscar'>"
        +"<td>1</td>"
        +"<td>2</td>"
        +"<td>3</td>"
        +"<td>4</td>"
        +"<td>5</td>"
    +"</tr> <tr class='oscar'>"
        +"<td>1</td>"
        +"<td>2</td>"
        +"<td>3</td>"
        +"<td>4</td>"
        +"<td>5</td>"
    +"</tr> <tr class='oscar'>"
        +"<td>1</td>"
        +"<td>2</td>"
        +"<td>3</td>"
        +"<td>4</td>"
        +"<td>5</td>"
    +"</tr>"
    +"</tr> <tr class='oscar'>"
        +"<td>1</td>"
        +"<td>2</td>"
        +"<td>3</td>"
        +"<td>4</td>"
        +"<td>5</td>"
    +"</tr>"
    +"</tr> <tr class='oscar'>"
    +"<td>1</td>"
    +"<td>2</td>"
    +"<td>3</td>"
    +"<td>4</td>"
    +"<td>5</td>"
+"</tr>"
+"</tr> <tr class='oscar'>"
+"<td>1</td>"
+"<td>2</td>"
+"<td>3</td>"
+"<td>4</td>"
+"<td>5</td>"
+"</tr>"
  +"</table>"
+"</center>";
 }
 function pero2() {
    document.getElementById("info").innerHTML = "" 
    +"<body class='cuerpo'>"
    +"<center><h2><p class='oscar'>LISTAR CARROS</p></h2></center>"
+"<center>"
   +"<form action='../../form-result.php' method='post' target='_blank'>"
    +"<p class='oscar'>"
     +"CONSULTAR <input type='search' name='busqueda' placeholder='identificacion, nombres, telefono...'>"
     +"<a class='piedra2' href=''>BUSCAR</a>"
    +"</p>"
  +"</form>"
+"</center>"
+"<style>"
    +"table,th,td{"
        +"border: 1px solid rgb(255, 250, 250);"
    +"}"
+"</style>"
+"<br>"
+"<center>"
+"<table class='and'>"
    +"<tr class='oscar'>"
      +"<th>N°</th>"
      +"<th>IDENTIFICACIÓN</th>"
      +"<th>NOMBRES</th>"
      +"<th>TELÉFONO</th>"
      +"<th>APELLIDOS</th>"
    +"</tr>"
    +"<tr class='oscar'>"
        +"<td>1</td>"
        +"<td>2</td>"
        +"<td>3</td>"
        +"<td>4</td>"
       +"<td>5</td>"
    +"</tr> <tr class='oscar'>"
        +"<td>1</td>"
        +"<td>2</td>"
        +"<td>3</td>"
        +"<td>4</td>"
        +"<td>5</td>"
    +"</tr> <tr class='oscar'>"
        +"<td>1</td>"
        +"<td>2</td>"
        +"<td>3</td>"
        +"<td>4</td>"
        +"<td>5</td>"
    +"</tr> <tr class='oscar'>"
        +"<td>1</td>"
        +"<td>2</td>"
        +"<td>3</td>"
        +"<td>4</td>"
        +"<td>5</td>"
    +"</tr>"
    +"</tr> <tr class='oscar'>"
        +"<td>1</td>"
        +"<td>2</td>"
        +"<td>3</td>"
        +"<td>4</td>"
        +"<td>5</td>"
    +"</tr>"
    +"</tr> <tr class='oscar'>"
    +"<td>1</td>"
    +"<td>2</td>"
    +"<td>3</td>"
    +"<td>4</td>"
    +"<td>5</td>"
+"</tr>"
+"</tr> <tr class='oscar'>"
+"<td>1</td>"
+"<td>2</td>"
+"<td>3</td>"
+"<td>4</td>"
+"<td>5</td>"
+"</tr>"
  +"</table>"
+"</center>";
 }
 function tiro() {
    document.getElementById("info").innerHTML = "" 
    +"<body class='cuerpo'><br>"
    +"<center>"
        +"<section>"
            +"<h2><p class='oscar'>REGISTRAR SERVICIOS</p></h2>"
            +"<input class='cons' type='text' name='TIPO DE DOCUMENTACIÓN'  placeholder='TIPO DE DOCUMENTACIÓN'><br>"
            +"<input class='cons' type='text' name='NOMBRES'  placeholder='NOMBRES'><br>"
            +"<input class='cons' type='text' name='APELLIDOS'  placeholder='APELLIDOS'><br>"
            +"<input class='cons' type='email' name='CORREO ELECTRONICO'  placeholder='CORREO ELECTRONICO'><br>"
            +"<input class='cons' type='text' name='CELULAR'  placeholder='CELULAR'><br><br><br><br>"
            +"<a class='piedra' href='menú.html'>REGISTRAR</a>"
        +"</section>"
    +"</center>"
 }
 function tiro1() {
    document.getElementById("info").innerHTML = "" 
    +"<body class='cuerpo'>"
    +"<center><h2><p class='oscar'>CONSULTAR SERVICIOS</p></h2></center>"
+"<center>"
   +"<form action='../../form-result.php' method='post' target='_blank'>"
    +"<p class='oscar'>"
     +"CONSULTAR <input type='search' name='busqueda' placeholder='identificacion, nombres, telefono...'>"
     +"<a class='piedra2' href=''>BUSCAR</a>"
    +"</p>"
  +"</form>"
+"</center>"
+"<style>"
    +"table,th,td{"
        +"border: 1px solid rgb(255, 250, 250);"
    +"}"
+"</style>"
+"<br>"
+"<center>"
+"<table class='and'>"
    +"<tr class='oscar'>"
      +"<th>N°</th>"
      +"<th>IDENTIFICACIÓN</th>"
      +"<th>NOMBRES</th>"
      +"<th>TELÉFONO</th>"
      +"<th>APELLIDOS</th>"
    +"</tr>"
    +"<tr class='oscar'>"
        +"<td>1</td>"
        +"<td>2</td>"
        +"<td>3</td>"
        +"<td>4</td>"
       +"<td>5</td>"
    +"</tr> <tr class='oscar'>"
        +"<td>1</td>"
        +"<td>2</td>"
        +"<td>3</td>"
        +"<td>4</td>"
        +"<td>5</td>"
    +"</tr> <tr class='oscar'>"
        +"<td>1</td>"
        +"<td>2</td>"
        +"<td>3</td>"
        +"<td>4</td>"
        +"<td>5</td>"
    +"</tr> <tr class='oscar'>"
        +"<td>1</td>"
        +"<td>2</td>"
        +"<td>3</td>"
        +"<td>4</td>"
        +"<td>5</td>"
    +"</tr>"
    +"</tr> <tr class='oscar'>"
        +"<td>1</td>"
        +"<td>2</td>"
        +"<td>3</td>"
        +"<td>4</td>"
        +"<td>5</td>"
    +"</tr>"
    +"</tr> <tr class='oscar'>"
    +"<td>1</td>"
    +"<td>2</td>"
    +"<td>3</td>"
    +"<td>4</td>"
    +"<td>5</td>"
+"</tr>"
+"</tr> <tr class='oscar'>"
+"<td>1</td>"
+"<td>2</td>"
+"<td>3</td>"
+"<td>4</td>"
+"<td>5</td>"
+"</tr>"
  +"</table>"
+"</center>";
 }
 function tiro2() {
    document.getElementById("info").innerHTML = "" 
    +"<body class='cuerpo'>"
    +"<center><h2><p class='oscar'>LISTAR SERVICIOS</p></h2></center>"
+"<center>"
   +"<form action='../../form-result.php' method='post' target='_blank'>"
    +"<p class='oscar'>"
     +"CONSULTAR <input type='search' name='busqueda' placeholder='identificacion, nombres, telefono...'>"
     +"<a class='piedra2' href=''>BUSCAR</a>"
    +"</p>"
  +"</form>"
+"</center>"
+"<style>"
    +"table,th,td{"
        +"border: 1px solid rgb(255, 250, 250);"
    +"}"
+"</style>"
+"<br>"
+"<center>"
+"<table class='and'>"
    +"<tr class='oscar'>"
      +"<th>N°</th>"
      +"<th>IDENTIFICACIÓN</th>"
      +"<th>NOMBRES</th>"
      +"<th>TELÉFONO</th>"
      +"<th>APELLIDOS</th>"
    +"</tr>"
    +"<tr class='oscar'>"
        +"<td>1</td>"
        +"<td>2</td>"
        +"<td>3</td>"
        +"<td>4</td>"
       +"<td>5</td>"
    +"</tr> <tr class='oscar'>"
        +"<td>1</td>"
        +"<td>2</td>"
        +"<td>3</td>"
        +"<td>4</td>"
        +"<td>5</td>"
    +"</tr> <tr class='oscar'>"
        +"<td>1</td>"
        +"<td>2</td>"
        +"<td>3</td>"
        +"<td>4</td>"
        +"<td>5</td>"
    +"</tr> <tr class='oscar'>"
        +"<td>1</td>"
        +"<td>2</td>"
        +"<td>3</td>"
        +"<td>4</td>"
        +"<td>5</td>"
    +"</tr>"
    +"</tr> <tr class='oscar'>"
        +"<td>1</td>"
        +"<td>2</td>"
        +"<td>3</td>"
        +"<td>4</td>"
        +"<td>5</td>"
    +"</tr>"
    +"</tr> <tr class='oscar'>"
    +"<td>1</td>"
    +"<td>2</td>"
    +"<td>3</td>"
    +"<td>4</td>"
    +"<td>5</td>"
+"</tr>"
+"</tr> <tr class='oscar'>"
+"<td>1</td>"
+"<td>2</td>"
+"<td>3</td>"
+"<td>4</td>"
+"<td>5</td>"
+"</tr>"
  +"</table>"
+"</center>";
 }
 function fero() {
    document.getElementById("info").innerHTML = "" 
    +"<body class='cuerpo'>"
    +"<center>"
      +"<section>"
        +"<h1><p class='oscar'>PARA QUEJAS O SUGERENCIAS</p></h1>"
        +"<h1><p class='oscar'>CONSULTAR CON EL ADMINISTRADOR</p></h1>"
        +"<h1><p class='oscar'>OSCAR ANDRES MARQUEZ VANEGAS</p></h1>"
        +"<h1><p class='oscar'>CORREÓ</p></h1>"
        +"<h1><p class='oscar'>oscarandresmarquezvanegas@gmail.com</p></h1>"
        +"<h1><p class='oscar'>NUMERO</p></h1>"
        +"<h1><p class='oscar'>3016484860</p></h1>"
       +"</section>"  
    +"</center>";
 }

 